USE DB_T2_VITOR_PIRES;

LOAD DATA LOCAL INFILE '/Users/stbsh/Documents/AULA BANCO DE DADOS/user.csv'
INTO TABLE USERS
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(NAME);